### ISSUE TITLE
Chapter and section titles do not seem to appear in the desired format

### ISSUE THREAD

**Issue by mi-homes** [Inventitech/phd-thesis-template#1]
Hi Moritz,

Thank you for the nice template. 
After compiling your template, all the chapter and section titles that I got look very different from that in your attached image and your thesis. 
Is it because you used a different font type or because of a missing package that I did not install in my LaTeX program?

Regards,
Minh Phuong Nguyen

**Comment by Inventitech** [comment]
Hi Minh,

Impossible to say from here. I would guess that you do not have the correct fonts installed. Do you have Libertinus and Inconsolata?

Moritz
